### ISSUE TITLE
Feature Request - -no-cache to support folder ignore

### ISSUE THREAD

**Issue by Tonio-lavanda** [apancutt/deploy-aws-s3-cloudfront#10]
Thanks for your package, it's working great, I was playing with no-cache and after finding the issue with --no-cache (https://github.com/apancutt/deploy-aws-s3-cloudfront/issues/9), I realised that I needed to provide an exact file path instead of a folder path

At the moment, the --no-cache option supports only specific files path.

It would be nice to be able to give a folder in input, all files within this folder should have the no-cache header.

I think (but you're the expert) that doing this is quite simple, you just need slightly improve the logic in `deploy.js`, instead of doing:

`CacheControl: noCache.includes(remotePath) ? 'no-cache' : undefined,`

You will need to check if `noCache` has at least one element that starts by `remotePath`

**Comment by apancutt** [comment]
Added in `2.3.1`.

The `--cache-control-no-cache` option now accepts wildcard paths.

For example, to prevent caching of the root `build` directory you can use `build/*`.
