### ISSUE TITLE
Can't deploy to s3 

### ISSUE THREAD

**Issue by Sheryorov** [apancutt/deploy-aws-s3-cloudfront#17]
Can't deploy react app to s3, its throw error : Source must be a path to a directory

Version:
`  "deploy-aws-s3-cloudfront": "^3.2.3",`

Script:
`    "deploy "deploy-aws-s3-cloudfront --acl public-read  --non-interactive --react --bucket bucketNAME
`

**Comment by apancutt** [comment]
Looks like you haven't run `yarn run build` first (i.e. you have no `build` directory).

**Comment by Sheryorov** [comment]
I have a build directory, but its called public

**Comment by Sheryorov** [comment]
How can i set direct build folder?

**Comment by apancutt** [comment]
You can't use the `react` option if you're using a custom build directory. You'll need to set the options explicitly:

`"deploy "deploy-aws-s3-cloudfront --acl public-read --non-interactive --source ./public/ --cache-control index.html:no-cache --bucket bucketNAME`

**Comment by Sheryorov** [comment]
i think we can close this issue
