### ISSUE TITLE
Using `--delete` option but excluding some paths

### ISSUE THREAD

**Issue by AntonUspehov** [apancutt/deploy-aws-s3-cloudfront#20]
Hi there,

I really need to use the `--delete` option that "Delete objects in AWS S3 that do not exist locally" BUT at the same time, I have to leave one directory even if this directory does not exist locally.

For example I have directory `docs` in S3-bucket with some files and I run:
```
deploy-aws-s3-cloudfront --bucket <some-bucket> --distribution <some-id> --react --non-interactive --delete
```
After that, I have my react-app in S3-bucket but don't have the directory `docs` there. But I have a business requirement to leave directory `docs` after any deployment.
And I can't remove option `--delete` because this will lead to unwanted garbage in the s3-bucket and unexpected consequences when requesting these outdated files from old deployments.

Can I do that in this version? Or maybe you know some workarounds for my case.
Thank you for your help!

**Comment by apancutt** [comment]
Currently not possible. Sounds like you're asking for a `--retain <path1> <path2> ...` option that allows users to provide path(s) to remote objects that should be retained when the `--delete` or `--soft-delete` options are used.

Feel free to submit a PR :)
