### ISSUE TITLE
Is there a way to set the content type of files?

### ISSUE THREAD

**Issue by tamj0rd2** [apancutt/deploy-aws-s3-cloudfront#22]
If using the aws cli to copy files to an S3 bucket, it's possible to set the content type of those files. Is there a way to do that with this tool?

**Comment by apancutt** [comment]
Content type is determined from the mime type ([see here](https://github.com/apancutt/deploy-aws-s3-cloudfront/blob/77c6135a88118774070a0196d7dc5a891b1e6f5e/src/changeset.js#L92)).

If you need to override the content type, that's not currently possible. Please submit a PR if this is needed.
